# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='article',
        ),
    ]
