# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
