# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160824_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2016, 8, 24, 16, 6, 0, 468000, tzinfo=utc)),
        ),
    ]
