# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160824_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
