# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 18:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160824_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
